import 'package:online_gym/models.dart/diet.dart';
import 'package:online_gym/models.dart/workout.dart';

DietPlan weightLossPlan = DietPlan(
  breakfast: 'Poha (flattened rice) with vegetables',
  breakfastImage: 'lib/assets/Vegetable-diet-poha-recipe@palates-desire.webp',
  betweenLB: 'Fruit chaat (mixed fruit salad)',
  betweenLBImage: 'lib/assets/Fruit-Chaat-Featured.jpg',
  lunch: 'Dal (lentil curry) with roti (whole wheat bread)',
  lunchImage: 'lib/assets/red-lentil-curry-square-2.jpg',
  evening: 'Tea with roasted chickpeas',
  eveningImage:
      'lib/assets/roasted-chickpeas-snack-garbanzo-beans-healthy-featuredimage-768x768.webp',
  supper: 'Vegetable khichdi (rice and lentil porridge)',
  supperImage: 'lib/assets/Basa-fish-curry-1.jpg',
);

DietPlan weightGainPlan = DietPlan(
  breakfast: 'Paratha (stuffed flatbread) with curd',
  breakfastImage:
      'lib/assets/paneer-paratha-stuffed-cottage-cheese-flatbread-recipe.jpg',
  betweenLB: 'Banana milkshake with nuts',
  betweenLBImage: 'lib/assets/peanut-butter-banana-smoothie-feaature.webp',
  lunch: 'Chicken curry with rice and salad',
  lunchImage: 'lib/assets/Chicken-Curry-Recipe-24.jpg',
  evening: 'Mango lassi (mango yogurt smoothie)',
  eveningImage: 'lib/assets/Mango-Lassi-1-of-1.jpeg',
  supper: 'Paneer (cottage cheese) tikka with naan (leavened bread)',
  supperImage: 'lib/assets/images (1).jpeg',
);

DietPlan weightMaintenancePlan = DietPlan(
  breakfast: 'Upma (semolina porridge) with coconut chutney',
  breakfastImage: 'lib/assets/images (2).jpeg',
  betweenLB: 'Sprouts chaat (mixed sprouts salad)',
  betweenLBImage: 'lib/assets/Sprouts-Salad-3.jpg',
  lunch: 'Vegetable pulao (spiced rice) with raita (yogurt side dish)',
  lunchImage: 'lib/assets/coconut-milk-pulao-recipe.jpg',
  evening: 'Masala chai (spiced tea) with roasted peanuts',
  eveningImage: 'lib/assets/images (3).jpeg',
  supper: 'Fish curry with steamed rice and vegetables',
  supperImage: 'lib/assets/Basa-fish-curry-1.jpg',
);

List<ExerciseModel> beginnerWorkouts = [
  // Monday
  ExerciseModel(
    day: 'Monday',
    workout1: 'Dumbbell Chest Press (Beginner)',
    workout1Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout1Instructions: 'Lie on a bench with dumbbells in each hand, palms facing forward. Push the weights up, extending your arms fully. Lower the weights slowly back to the starting position.',
    workout2: 'Push-Ups (Knee)',
    workout2Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout2Instructions: 'Start in a plank position with your knees on the ground. Lower your body by bending your elbows, then push back up to the starting position.',
    workout3: 'Dumbbell Rows (Bent Over)',
    workout3Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout3Instructions: 'Stand with dumbbells in hand, bend at the waist with your back straight, and pull the weights up towards your chest. Lower the weights back down slowly.',
    workout4: 'Crunches',
    workout4Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout4Instructions: 'Lie on your back with knees bent, hands behind your head. Lift your upper body towards your knees, engaging your core muscles.',
    workout5: 'Dumbbell Shoulder Press (Beginner)',
    workout5Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout5Instructions: 'Hold dumbbells at shoulder height, palms facing forward. Press the weights up above your head, then lower them back down to shoulder height.',
    workout6: 'Mountain Climbers (Slow)',
    workout6Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout6Instructions: 'Start in a plank position. Bring one knee towards your chest, then switch legs in a running motion, keeping your core engaged.',
    workout7: 'Dumbbell Lunges (Reverse)',
    workout7Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout7Instructions: 'Hold dumbbells at your sides, step back with one foot, bending both knees until the back knee nearly touches the ground. Return to standing position.',
    workout8: 'Russian Twists (Light)',
    workout8Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout8Instructions: 'Sit on the floor with knees bent, lean back slightly, holding a weight or medicine ball. Twist your torso from side to side, touching the weight to the floor beside you.',
    sets: 3,
    reps: 10,
  ),
  // Tuesday
  ExerciseModel(
    day: 'Tuesday',
    workout1: 'Dumbbell Bicep Curls (Beginner)',
    workout1Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout1Instructions: 'Stand with dumbbells in hand, palms facing forward. Curl the weights towards your shoulders, keeping your elbows close to your body.',
    workout2: 'Pull-Ups (Assisted)',
    workout2Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout2Instructions: 'Use a pull-up assist machine or resistance bands. Grab the bar with palms facing away, pull your body up until your chin is above the bar, then lower back down.',
    workout3: 'Dumbbell Tricep Extensions (Beginner)',
    workout3Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout3Instructions: 'Hold a dumbbell overhead with both hands. Bend your elbows, lowering the weight behind your head, then straighten your arms to lift the weight back up.',
    workout4: 'Leg Raises',
    workout4Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout4Instructions: 'Lie on your back with legs straight. Lift your legs towards the ceiling, keeping them straight, then lower them back down slowly without touching the ground.',
    workout5: 'Dumbbell Squats (Beginner)',
    workout5Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout5Instructions: 'Hold dumbbells at your sides, feet shoulder-width apart. Lower into a squat by bending your knees, keeping your back straight, then return to standing.',
    workout6: 'Plank (30 seconds)',
    workout6Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout6Instructions: 'Get into a push-up position but with your weight on your forearms. Hold your body in a straight line from head to heels, engaging your core muscles.',
    workout7: 'Dumbbell Deadlifts (Beginner)',
    workout7Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout7Instructions: 'Hold dumbbells in front of your thighs, feet hip-width apart. Bend at the hips, keeping your back straight, lower the weights towards the ground, then return to standing.',
    workout8: 'Side Plank (Both Sides)',
    workout8Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout8Instructions: 'Lie on your side, propped up on one forearm, with legs stacked. Lift your hips off the ground, forming a straight line from head to heels. Hold, then switch sides.',
    sets: 3,
    reps: 10,
  ),
  // Wednesday
  ExerciseModel(
    day: 'Wednesday',
    workout1: 'Dumbbell Bench Press (Beginner)',
    workout1Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout1Instructions: 'Lie on a bench with dumbbells in each hand, palms facing forward. Press the weights up, extending your arms fully. Lower the weights slowly back to the starting position.',
    workout2: 'Dips (Assisted)',
    workout2Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout2Instructions: 'Use a dip assist machine or chair. Lower your body by bending your elbows, then push back up to the starting position.',
    workout3: 'Dumbbell Lateral Raises (Beginner)',
    workout3Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout3Instructions: 'Hold dumbbells at your sides, palms facing in. Lift the weights out to the sides until they reach shoulder height, then lower them back down.',
    workout4: 'Sit-Ups',
    workout4Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout4Instructions: 'Lie on your back with knees bent, feet flat on the ground. Lift your upper body towards your knees, engaging your core muscles.',
    workout5: 'Dumbbell Step-Ups (Beginner)',
    workout5Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout5Instructions: 'Hold dumbbells at your sides, stand in front of a step or platform. Step up with one foot, then bring the other foot up. Step back down and repeat on the other side.',
    workout6: 'Hanging Leg Raises (Knee)',
    workout6Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout6Instructions: 'Hang from a pull-up bar, legs straight. Lift your legs towards your chest, then lower them back down without swinging.',
    workout7: 'Dumbbell Lunges (Beginner)',
    workout7Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout7Instructions: 'Hold dumbbells at your sides, step forward with one foot, bending both knees until the front thigh is parallel to the ground. Return to standing position.',
    workout8: 'Russian Twists (Light)',
    workout8Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout8Instructions: 'Sit on the floor with knees bent, lean back slightly, holding a weight or medicine ball. Twist your torso from side to side, touching the weight to the floor beside you.',
    sets: 3,
    reps: 10,
  ),
  // Thursday
  ExerciseModel(
    day: 'Thursday',
    workout1: 'Dumbbell Shoulder Press (Beginner)',
    workout1Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout1Instructions: 'Hold dumbbells at shoulder height, palms facing forward. Press the weights up above your head, then lower them back down to shoulder height.',
    workout2: 'Chin-Ups (Assisted)',
    workout2Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout2Instructions: 'Use a chin-up assist machine or resistance bands. Grab the bar with palms facing towards you, pull your body up until your chin is above the bar, then lower back down.',
    workout3: 'Dumbbell Hammer Curls (Beginner)',
    workout3Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout3Instructions: 'Stand with dumbbells in hand, palms facing each other. Curl the weights towards your shoulders, keeping your elbows close to your body.',
    workout4: 'Plank (30 seconds)',
    workout4Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout4Instructions: 'Get into a push-up position but with your weight on your forearms. Hold your body in a straight line from head to heels, engaging your core muscles.',
    workout5: 'Dumbbell Lunges (Beginner)',
    workout5Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout5Instructions: 'Hold dumbbells at your sides, step forward with one foot, bending both knees until the front thigh is parallel to the ground. Return to standing position.',
    workout6: 'Reverse Crunches',
    workout6Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout6Instructions: 'Lie on your back with knees bent and feet off the ground. Bring your knees towards your chest, lifting your hips off the ground.',
    workout7: 'Dumbbell Squats (Beginner)',
    workout7Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout7Instructions: 'Hold dumbbells at your sides, feet shoulder-width apart. Lower into a squat by bending your knees, keeping your back straight, then return to standing.',
    workout8: 'Mountain Climbers (Slow)',
    workout8Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout8Instructions: 'Start in a plank position. Bring one knee towards your chest, then switch legs in a running motion, keeping your core engaged.',
    sets: 3,
    reps: 10,
  ),
  // Friday
  ExerciseModel(
    day: 'Friday',
    workout1: 'Dumbbell Deadlifts (Beginner)',
    workout1Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout1Instructions: 'Hold dumbbells in front of your thighs, feet hip-width apart. Bend at the hips, keeping your back straight, lower the weights towards the ground, then return to standing.',
    workout2: 'Push-Ups (Knee)',
    workout2Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout2Instructions: 'Start in a plank position with your knees on the ground. Lower your body by bending your elbows, then push back up to the starting position.',
    workout3: 'Dumbbell Chest Flyes (Beginner)',
    workout3Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout3Instructions: 'Lie on a bench with dumbbells in each hand, palms facing each other. Open your arms out to the sides, then bring them back together over your chest.',
    workout4: 'Leg Raises',
    workout4Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout4Instructions: 'Lie on your back with legs straight. Lift your legs towards the ceiling, keeping them straight, then lower them back down slowly without touching the ground.',
    workout5: 'Dumbbell Lunges (Beginner)',
    workout5Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout5Instructions: 'Hold dumbbells at your sides, step forward with one foot, bending both knees until the front thigh is parallel to the ground. Return to standing position.',
    workout6: 'Plank (30 seconds)',
    workout6Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout6Instructions: 'Get into a push-up position but with your weight on your forearms. Hold your body in a straight line from head to heels, engaging your core muscles.',
    workout7: 'Dumbbell Bicep Curls (Beginner)',
    workout7Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout7Instructions: 'Stand with dumbbells in hand, palms facing forward. Curl the weights towards your shoulders, keeping your elbows close to your body.',
    workout8: 'Russian Twists (Light)',
    workout8Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout8Instructions: 'Sit on the floor with knees bent, lean back slightly, holding a weight or medicine ball. Twist your torso from side to side, touching the weight to the floor beside you.',
    sets: 3,
    reps: 10,
  ),
  // Saturday
  ExerciseModel(
    day: 'Saturday',
    workout1: 'Dumbbell Tricep Extensions (Beginner)',
    workout1Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout1Instructions: 'Hold a dumbbell overhead with both hands. Bend your elbows, lowering the weight behind your head, then straighten your arms to lift the weight back up.',
    workout2: 'Pull-Ups (Assisted)',
    workout2Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout2Instructions: 'Use a pull-up assist machine or resistance bands. Grab the bar with palms facing away, pull your body up until your chin is above the bar, then lower back down.',
    workout3: 'Dumbbell Squats (Beginner)',
    workout3Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout3Instructions: 'Hold dumbbells at your sides, feet shoulder-width apart. Lower into a squat by bending your knees, keeping your back straight, then return to standing.',
    workout4: 'Bicycle Crunches',
    workout4Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout4Instructions: 'Lie on your back with knees bent, hands behind your head. Bring one elbow towards the opposite knee, alternating sides in a pedaling motion.',
    workout5: 'Dumbbell Shoulder Press (Beginner)',
    workout5Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout5Instructions: 'Hold dumbbells at shoulder height, palms facing forward. Press the weights up above your head, then lower them back down to shoulder height.',
    workout6: 'Plank (30 seconds)',
    workout6Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout6Instructions: 'Get into a push-up position but with your weight on your forearms. Hold your body in a straight line from head to heels, engaging your core muscles.',
    workout7: 'Dumbbell Lunges (Beginner)',
    workout7Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout7Instructions: 'Hold dumbbells at your sides, step forward with one foot, bending both knees until the front thigh is parallel to the ground. Return to standing position.',
    workout8: 'Russian Twists (Light)',
    workout8Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout8Instructions: 'Sit on the floor with knees bent, lean back slightly, holding a weight or medicine ball. Twist your torso from side to side, touching the weight to the floor beside you.',
    sets: 3,
    reps: 10,
  ),
];

List<ExerciseModel> intermediateWorkouts = [
  ExerciseModel(
    day: 'Monday',
    workout1: 'Dumbbell Chest Press (Intermediate)',
    workout1Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout1Instructions: 'Lie on a bench with dumbbells in hand, arms extended above chest. Lower the weights to chest level, then press them back up explosively.',
    workout2: 'Diamond Push-Ups',
    workout2Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout2Instructions: 'Assume a push-up position with hands close together under your chest. Lower your body until your chest nearly touches your hands, then push back up.',
    workout3: 'Dumbbell Rows (One Arm)',
    workout3Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout3Instructions: 'Stand with one knee and hand on a bench, holding a dumbbell in the other hand. Pull the weight towards your hip, then lower it back down.',
    workout4: 'Leg Raises',
    workout4Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout4Instructions: 'Lie on your back with legs extended. Lift your legs towards the ceiling, then lower them back down without touching the floor.',
    workout5: 'Dumbbell Shoulder Press (Intermediate)',
    workout5Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout5Instructions: 'Hold dumbbells at shoulder height, palms facing forward. Press the weights up above your head explosively, then lower them back down to shoulder height.',
    workout6: 'Mountain Climbers (Moderate)',
    workout6Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout6Instructions: 'Assume a push-up position. Alternately drive your knees towards your chest, keeping your back flat and core engaged.',
    workout7: 'Dumbbell Lunges (Forward)',
    workout7Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout7Instructions: 'Hold dumbbells at your sides. Step forward with one foot, lowering your body until both knees are at 90-degree angles, then push back to standing.',
    workout8: 'Russian Twists (Moderate)',
    workout8Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout8Instructions: 'Sit on the floor with knees bent, lean back slightly, holding a weight or medicine ball. Twist your torso from side to side, touching the weight to the floor beside you.',
    sets: 4,
    reps: 12,
  ),
  ExerciseModel(
    day: 'Tuesday',
    workout1: 'Dumbbell Bicep Curls (Intermediate)',
    workout1Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout1Instructions: 'Stand with dumbbells at your sides, palms facing forward. Curl the weights towards your shoulders, then lower them back down with control.',
    workout2: 'Pull-Ups (Neutral Grip)',
    workout2Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout2Instructions: 'Grab the pull-up bar with palms facing each other. Pull your body up until your chin clears the bar, then lower back down with control.',
    workout3: 'Dumbbell Tricep Extensions (Intermediate)',
    workout3Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout3Instructions: 'Hold a dumbbell overhead with both hands. Bend your elbows, lowering the weight behind your head, then straighten your arms to lift it back up.',
    workout4: 'Leg Raises (Twist)',
    workout4Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout4Instructions: 'Lie on your back with legs extended. Lift your legs towards the ceiling while twisting your torso to bring one elbow towards the opposite knee.',
    workout5: 'Dumbbell Squats (Intermediate)',
    workout5Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout5Instructions: 'Hold dumbbells at your sides, feet shoulder-width apart. Lower into a squat by bending your knees, keeping your back straight, then return to standing.',
    workout6: 'Plank (45 seconds)',
    workout6Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout6Instructions: 'Get into a push-up position but with your weight on your forearms. Hold your body in a straight line from head to heels, engaging your core muscles.',
    workout7: 'Dumbbell Deadlifts (Intermediate)',
    workout7Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout7Instructions: 'Hold dumbbells in front of your thighs, palms facing your body. Hinge at your hips, lowering the weights towards the ground, then stand back up.',
    workout8: 'Side Plank (Extended)',
    workout8Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout8Instructions: 'Lie on your side with your elbow directly beneath your shoulder. Lift your hips until your body forms a straight line, then hold.',
    sets: 4,
    reps: 12,
  ),
  ExerciseModel(
    day: 'Wednesday',
    workout1: 'Dumbbell Bench Press (Intermediate)',
    workout1Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout1Instructions: 'Lie on a bench with dumbbells in hand, arms extended above chest. Lower the weights to chest level, then press them back up explosively.',
    workout2: 'Dips (Tricep Focus)',
    workout2Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout2Instructions: 'Hold onto parallel bars with arms extended. Lower your body by bending your elbows, then push back up explosively.',
    workout3: 'Dumbbell Lateral Raises (Intermediate)',
    workout3Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout3Instructions: 'Stand with dumbbells at your sides, palms facing your body. Raise the weights out to the sides until they reach shoulder height, then lower them back down.',
    workout4: 'Sit-Ups (Twist)',
    workout4Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout4Instructions: 'Lie on your back with knees bent and hands behind your head. Crunch up, twisting your torso to bring one elbow towards the opposite knee.',
    workout5: 'Dumbbell Step-Ups (Intermediate)',
    workout5Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout5Instructions: 'Hold dumbbells at your sides, facing a step or platform. Step up with one foot, then bring the other foot up, then step back down.',
    workout6: 'Hanging Leg Raises (Straight)',
    workout6Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout6Instructions: 'Hang from a pull-up bar with legs straight. Raise your legs towards the ceiling, then lower them back down without swinging.',
    workout7: 'Dumbbell Lunges (Intermediate)',
    workout7Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout7Instructions: 'Hold dumbbells at your sides. Step forward with one foot, lowering your body until both knees are at 90-degree angles, then push back to standing.',
    workout8: 'Russian Twists (Moderate)',
    workout8Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout8Instructions: 'Sit on the floor with knees bent, lean back slightly, holding a weight or medicine ball. Twist your torso from side to side, touching the weight to the floor beside you.',
    sets: 4,
    reps: 12,
  ),
  ExerciseModel(
    day: 'Thursday',
    workout1: 'Dumbbell Shoulder Press (Intermediate)',
    workout1Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout1Instructions: 'Hold dumbbells at shoulder height, palms facing forward. Press the weights up above your head explosively, then lower them back down to shoulder height.',
    workout2: 'Chin-Ups (Wide Grip)',
    workout2Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout2Instructions: 'Grab the pull-up bar with palms facing away from you, wider than shoulder-width apart. Pull your body up until your chin clears the bar, then lower back down.',
    workout3: 'Dumbbell Hammer Curls (Intermediate)',
    workout3Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout3Instructions: 'Stand with dumbbells at your sides, palms facing each other. Curl the weights towards your shoulders, keeping your elbows close to your body.',
    workout4: 'Plank (45 seconds)',
    workout4Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout4Instructions: 'Get into a push-up position but with your weight on your forearms. Hold your body in a straight line from head to heels, engaging your core muscles.',
    workout5: 'Dumbbell Lunges (Intermediate)',
    workout5Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout5Instructions: 'Hold dumbbells at your sides. Step forward with one foot, lowering your body until both knees are at 90-degree angles, then push back to standing.',
    workout6: 'Reverse Crunches (Extended)',
    workout6Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout6Instructions: 'Lie on your back with knees bent and hands behind your head. Lift your hips off the ground while bringing your knees towards your chest.',
    workout7: 'Dumbbell Squats (Intermediate)',
    workout7Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout7Instructions: 'Hold dumbbells at your sides, feet shoulder-width apart. Lower into a squat by bending your knees, keeping your back straight, then return to standing.',
    workout8: 'Mountain Climbers (Moderate)',
    workout8Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout8Instructions: 'Assume a push-up position. Alternately drive your knees towards your chest, keeping your back flat and core engaged.',
    sets: 4,
    reps: 12,
  ),
  ExerciseModel(
    day: 'Friday',
    workout1: 'Dumbbell Deadlifts (Intermediate)',
    workout1Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout1Instructions: 'Hold dumbbells in front of your thighs, palms facing your body. Hinge at your hips, lowering the weights towards the ground, then stand back up.',
    workout2: 'Push-Ups (Regular)',
    workout2Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout2Instructions: 'Assume a push-up position with hands slightly wider than shoulder-width apart. Lower your body until your chest nearly touches the ground, then push back up.',
    workout3: 'Dumbbell Chest Flyes (Intermediate)',
    workout3Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout3Instructions: 'Lie on a bench with dumbbells in hand, arms extended above chest. Open your arms wide, lowering the weights out to the sides, then bring them back together over your chest.',
    workout4: 'Leg Raises (Twist)',
    workout4Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout4Instructions: 'Lie on your back with knees bent and hands behind your head. Crunch up, twisting your torso to bring one elbow towards the opposite knee.',
    workout5: 'Dumbbell Lunges (Intermediate)',
    workout5Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout5Instructions: 'Hold dumbbells at your sides. Step forward with one foot, lowering your body until both knees are at 90-degree angles, then push back to standing.',
    workout6: 'Plank (45 seconds)',
    workout6Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout6Instructions: 'Get into a push-up position but with your weight on your forearms. Hold your body in a straight line from head to heels, engaging your core muscles.',
    workout7: 'Dumbbell Bicep Curls (Intermediate)',
    workout7Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout7Instructions: 'Stand with dumbbells at your sides, palms facing forward. Curl the weights towards your shoulders, then lower them back down with control.',
    workout8: 'Russian Twists (Moderate)',
    workout8Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout8Instructions: 'Sit on the floor with knees bent, lean back slightly, holding a weight or medicine ball. Twist your torso from side to side, touching the weight to the floor beside you.',
    sets: 4,
    reps: 12,
  ),
  ExerciseModel(
    day: 'Saturday',
    workout1: 'Dumbbell Tricep Extensions (Intermediate)',
    workout1Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout1Instructions: 'Hold a dumbbell overhead with both hands. Bend your elbows, lowering the weight behind your head, then straighten your arms to lift it back up.',
    workout2: 'Pull-Ups (Regular Grip)',
    workout2Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout2Instructions: 'Grab the pull-up bar with palms facing away from you, about shoulder-width apart. Pull your body up until your chin clears the bar, then lower back down.',
    workout3: 'Dumbbell Squats (Intermediate)',
    workout3Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout3Instructions: 'Hold dumbbells at your sides, feet shoulder-width apart. Lower into a squat by bending your knees, keeping your back straight, then return to standing.',
    workout4: 'Bicycle Crunches (Extended)',
    workout4Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout4Instructions: 'Lie on your back with knees bent and hands behind your head. Bring one knee towards your chest while twisting your torso to bring the opposite elbow towards it.',
    workout5: 'Dumbbell Shoulder Press (Intermediate)',
    workout5Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout5Instructions: 'Hold dumbbells at shoulder height, palms facing forward. Press the weights up above your head explosively, then lower them back down to shoulder height.',
    workout6: 'Plank (45 seconds)',
    workout6Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout6Instructions: 'Get into a push-up position but with your weight on your forearms. Hold your body in a straight line from head to heels, engaging your core muscles.',
    workout7: 'Dumbbell Lunges (Intermediate)',
    workout7Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout7Instructions: 'Hold dumbbells at your sides. Step forward with one foot, lowering your body until both knees are at 90-degree angles, then push back to standing.',
    workout8: 'Russian Twists (Moderate)',
    workout8Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout8Instructions: 'Sit on the floor with knees bent, lean back slightly, holding a weight or medicine ball. Twist your torso from side to side, touching the weight to the floor beside you.',
    sets: 4,
    reps: 12,
  ),
];

List<ExerciseModel> advancedWorkouts = [
  // Monday
  ExerciseModel(
    day: 'Monday',
    workout1: 'Dumbbell Chest Press (Advanced)',
    workout1Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout1Instructions: 'Lie on a bench with dumbbells in each hand, palms facing forward. Press the weights up explosively, extending your arms fully. Lower the weights slowly back to the starting position.',
    workout2: 'Explosive Push-Ups',
    workout2Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout2Instructions: 'Start in a plank position. Lower your body explosively by bending your elbows, then push off the ground with force to lift your hands off briefly. Land softly and repeat.',
    workout3: 'Pull-Ups (Wide Grip)',
    workout3Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout3Instructions: 'Grab the pull-up bar with palms facing away and wider than shoulder-width apart. Pull your body up until your chin is above the bar, then lower back down.',
    workout4: 'Hanging Leg Raises (Extended)',
    workout4Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout4Instructions: 'Hang from a pull-up bar, legs straight. Lift your legs towards the ceiling, keeping them straight and lifting them higher than parallel to the ground.',
    workout5: 'Dumbbell Shoulder Press (Advanced)',
    workout5Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout5Instructions: 'Hold dumbbells at shoulder height, palms facing forward. Press the weights up above your head explosively, then lower them back down to shoulder height.',
    workout6: 'Mountain Climbers (Fast)',
    workout6Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout6Instructions: 'Start in a plank position. Quickly alternate bringing each knee towards your chest in a running motion, keeping your core engaged and hips stable.',
    workout7: 'Dumbbell Lunges (Jumping)',
    workout7Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout7Instructions: 'Hold dumbbells at your sides. Jump up explosively, switching your feet in mid-air so you land in a lunge position with the opposite foot forward.',
    workout8: 'Russian Twists (Advanced)',
    workout8Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout8Instructions: 'Sit on the floor with knees bent, lean back slightly, holding a weight or medicine ball. Twist your torso from side to side explosively, touching the weight to the floor beside you.',
    sets: 4,
    reps: 15,
  ),
  // Tuesday
  ExerciseModel(
    day: 'Tuesday',
    workout1: 'Dumbbell Bicep Curls (Advanced)',
    workout1Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout1Instructions: 'Stand with dumbbells in hand, palms facing forward. Curl the weights towards your shoulders explosively, keeping your elbows close to your body.',
    workout2: 'Pull-Ups (Close Grip)',
    workout2Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout2Instructions: 'Grab the pull-up bar with palms facing towards you and hands close together. Pull your body up until your chin is above the bar, then lower back down.',
    workout3: 'Dumbbell Tricep Extensions (Advanced)',
    workout3Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout3Instructions: 'Hold a dumbbell overhead with both hands. Bend your elbows, lowering the weight behind your head explosively, then straighten your arms to lift the weight back up.',
    workout4: 'Leg Raises (Extended)',
    workout4Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout4Instructions: 'Lie on your back with legs straight. Lift your legs towards the ceiling, keeping them straight and lifting them higher than parallel to the ground, then lower them back down slowly.',
    workout5: 'Dumbbell Squats (Advanced)',
    workout5Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout5Instructions: 'Hold dumbbells at your sides, feet shoulder-width apart. Lower into a squat explosively by bending your knees, keeping your back straight, then return to standing.',
    workout6: 'Plank (60 seconds)',
    workout6Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout6Instructions: 'Get into a push-up position but with your weight on your forearms. Hold your body in a straight line from head to heels, engaging your core muscles.',
    workout7: 'Dumbbell Deadlifts (Advanced)',
    workout7Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout7Instructions: 'Hold dumbbells in front of your thighs, feet hip-width apart. Bend at the hips, keeping your back straight, lower the weights towards the ground explosively, then return to standing.',
    workout8: 'Side Plank (Full)',
    workout8Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout8Instructions: 'Lie on your side, propped up on one hand with arm extended. Lift your hips off the ground, forming a straight line from head to heels. Hold, then switch sides.',
    sets: 4,
    reps: 15,
  ),
  // Wednesday
  ExerciseModel(
    day: 'Wednesday',
    workout1: 'Dumbbell Bench Press (Advanced)',
    workout1Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout1Instructions: 'Lie on a bench with dumbbells in each hand, palms facing forward. Press the weights up explosively, extending your arms fully. Lower the weights slowly back to the starting position.',
    workout2: 'Dips (Weighted)',
    workout2Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout2Instructions: 'Use a dip belt or hold a dumbbell between your legs. Lower your body until your elbows are at 90 degrees, then press back up explosively to the starting position.',
    workout3: 'Dumbbell Lateral Raises (Advanced)',
    workout3Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout3Instructions: 'Stand with dumbbells at your sides, palms facing inward. Lift the weights out to the sides until they are at shoulder height, then lower back down slowly.',
    workout4: 'Sit-Ups (Extended)',
    workout4Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout4Instructions: 'Anchor your feet and lower back to the floor. Sit all the way up explosively, reaching your hands towards your feet, then lower back down slowly.',
    workout5: 'Dumbbell Step-Ups (Advanced)',
    workout5Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout5Instructions: 'Hold dumbbells at your sides, stand facing a bench or elevated platform. Step up explosively onto the bench with one foot, then step back down and switch legs.',
    workout6: 'Hanging Leg Raises (Twist)',
    workout6Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout6Instructions: 'Hang from a pull-up bar, legs straight. Lift your legs towards the ceiling while twisting your hips to one side, then return to center and lower your legs back down.',
    workout7: 'Dumbbell Lunges (Advanced)',
    workout7Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout7Instructions: 'Hold dumbbells at your sides. Step forward with one foot explosively, bending both knees until the front thigh is parallel to the ground. Push back to standing.',
    workout8: 'Russian Twists (Advanced)',
    workout8Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout8Instructions: 'Sit on the floor with knees bent, lean back slightly, holding a weight or medicine ball. Twist your torso from side to side explosively, touching the weight to the floor beside you.',
    sets: 4,
    reps: 15,
  ),
  // Thursday
  ExerciseModel(
    day: 'Thursday',
    workout1: 'Dumbbell Shoulder Press (Advanced)',
    workout1Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout1Instructions: 'Hold dumbbells at shoulder height, palms facing forward. Press the weights up above your head explosively, then lower them back down to shoulder height.',
    workout2: 'Chin-Ups (Weighted)',
    workout2Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout2Instructions: 'Use a chin-up belt or hold a dumbbell between your feet. Grab the bar with palms facing towards you. Pull your body up until your chin is above the bar, then lower back down.',
    workout3: 'Dumbbell Hammer Curls (Advanced)',
    workout3Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout3Instructions: 'Stand with dumbbells in hand, palms facing each other. Curl the weights towards your shoulders explosively, keeping your elbows close to your body.',
    workout4: 'Plank (60 seconds)',
    workout4Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout4Instructions: 'Get into a push-up position but with your weight on your forearms. Hold your body in a straight line from head to heels, engaging your core muscles.',
    workout5: 'Dumbbell Lunges (Advanced)',
    workout5Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout5Instructions: 'Hold dumbbells at your sides. Step forward with one foot explosively, bending both knees until the front thigh is parallel to the ground. Push back to standing.',
    workout6: 'Reverse Crunches (Extended)',
    workout6Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout6Instructions: 'Lie on your back with knees bent and feet off the ground. Bring your knees towards your chest explosively, lifting your hips off the ground.',
    workout7: 'Dumbbell Squats (Advanced)',
    workout7Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout7Instructions: 'Hold dumbbells at your sides, feet shoulder-width apart. Lower into a squat explosively by bending your knees, keeping your back straight, then return to standing.',
    workout8: 'Mountain Climbers (Fast)',
    workout8Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout8Instructions: 'Start in a plank position. Quickly alternate bringing each knee towards your chest in a running motion, keeping your core engaged and hips stable.',
    sets: 4,
    reps: 15,
  ),
  // Friday
  ExerciseModel(
    day: 'Friday',
    workout1: 'Dumbbell Deadlifts (Advanced)',
    workout1Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout1Instructions: 'Hold dumbbells in front of your thighs, feet hip-width apart. Bend at the hips, keeping your back straight, lower the weights towards the ground explosively, then return to standing.',
    workout2: 'Push-Ups (Explosive)',
    workout2Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout2Instructions: 'Start in a plank position. Lower your body explosively by bending your elbows, then push off the ground with force to lift your hands off briefly. Land softly and repeat.',
    workout3: 'Dumbbell Chest Flyes (Advanced)',
    workout3Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout3Instructions: 'Lie on a bench with dumbbells in each hand, palms facing each other. Open your arms out to the sides explosively, then bring them back together over your chest.',
    workout4: 'Leg Raises (Extended)',
    workout4Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout4Instructions: 'Lie on your back with legs straight. Lift your legs towards the ceiling, keeping them straight and lifting them higher than parallel to the ground, then lower them back down slowly.',
    workout5: 'Dumbbell Lunges (Advanced)',
    workout5Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout5Instructions: 'Hold dumbbells at your sides. Step forward with one foot explosively, bending both knees until the front thigh is parallel to the ground. Push back to standing.',
    workout6: 'Plank (60 seconds)',
    workout6Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout6Instructions: 'Get into a push-up position but with your weight on your forearms. Hold your body in a straight line from head to heels, engaging your core muscles.',
    workout7: 'Dumbbell Bicep Curls (Advanced)',
    workout7Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout7Instructions: 'Stand with dumbbells in hand, palms facing forward. Curl the weights towards your shoulders explosively, keeping your elbows close to your body.',
    workout8: 'Russian Twists (Advanced)',
    workout8Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout8Instructions: 'Sit on the floor with knees bent, lean back slightly, holding a weight or medicine ball. Twist your torso from side to side explosively, touching the weight to the floor beside you.',
    sets: 4,
    reps: 15,
  ),
  // Saturday
  ExerciseModel(
    day: 'Saturday',
    workout1: 'Dumbbell Tricep Extensions (Advanced)',
    workout1Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout1Instructions: 'Hold a dumbbell overhead with both hands. Bend your elbows, lowering the weight behind your head explosively, then straighten your arms to lift the weight back up.',
    workout2: 'Pull-Ups (Wide Grip)',
    workout2Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout2Instructions: 'Grab the pull-up bar with palms facing away and wider than shoulder-width apart. Pull your body up until your chin is above the bar, then lower back down.',
    workout3: 'Dumbbell Squats (Advanced)',
    workout3Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout3Instructions: 'Hold dumbbells at your sides, feet shoulder-width apart. Lower into a squat explosively by bending your knees, keeping your back straight, then return to standing.',
    workout4: 'Bicycle Crunches (Extended)',
    workout4Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout4Instructions: 'Lie on your back with knees bent and hands behind your head. Bring one elbow towards the opposite knee while straightening the other leg, then switch sides in a pedaling motion.',
    workout5: 'Dumbbell Shoulder Press (Advanced)',
    workout5Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout5Instructions: 'Hold dumbbells at shoulder height, palms facing forward. Press the weights up above your head explosively, then lower them back down to shoulder height.',
    workout6: 'Plank (60 seconds)',
    workout6Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout6Instructions: 'Get into a push-up position but with your weight on your forearms. Hold your body in a straight line from head to heels, engaging your core muscles.',
    workout7: 'Dumbbell Lunges (Advanced)',
    workout7Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout7Instructions: 'Hold dumbbells at your sides. Step forward with one foot explosively, bending both knees until the front thigh is parallel to the ground. Push back to standing.',
    workout8: 'Russian Twists (Advanced)',
    workout8Image: "lib/assets/young-bodybuilder-doing-squats-workout-at-the-royalty-free-image-1680033534 (1).jpg",
    workout8Instructions: 'Sit on the floor with knees bent, lean back slightly, holding a weight or medicine ball. Twist your torso from side to side explosively, touching the weight to the floor beside you.',
    sets: 4,
    reps: 15,
  ),
];
